name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Kód letöltése
      - name: Checkout repository
        uses: actions/checkout@v3

      # Python környezet beállítása
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Függőségek telepítése
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Tesztek futtatása Pytest-tel
      - name: Run Pytest
        run: pytest --junit-xml=test-results.xml

      # Teszt eredmények publikálása (opcionális)
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test-results.xml
